version: "3"

services:
  api:
    container_name: uadegram
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/api
  mongo:
    container_name: uadegram_db
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null 